### ISSUE TITLE
Option for response_format (e.g. to create subtitles)

### ISSUE THREAD

**Issue by leotulipan** [felixbade/transcribe#8]
See https://platform.openai.com/docs/api-reference/audio

The format of the transcript output, in one of these options:

-  json
-  text
- srt
-  verbose_json
- vtt

Especially SRT (subtitle format with timings) seems to be interesting

(while you're at it you could also add the "temperature" option)

Cheers
Leo

**Comment by felixbade** [comment]
Not sure if raw options make sense, but with and without timestamps for sure. Would SRT format specifically be useful for you so you can import it directly? Because I think the timestamps could also be formatted in a more human friendly way (e.g. different font size, spacings, colors, …)

**Comment by leotulipan** [comment]
See my PR https://github.com/felixbade/transcribe/pull/9
